### PR TITLE
Add spec file pattern setting and refactor

### LINKED ISSUE #4: Add setting to specify spec suffix
In my team we name our spec files like this: `file-spec.js` instead of `file.spec.js`. I think that would be great to define the suffix style in settings.

### PR DESCRIPTION
**Pull request by Nautigsam**
I added the setting to specify the pattern of a spec file. I also simplified the code, I am open to critics, of course.
It is meant to fix #4

### CODE REVIEW

**Comment by lourenci** [comment]
Hi, the extension must be able to open any spec file, like Intellij IDE. This change has broken a lot of patterns.

But, if your file is in the same folder of your code, you can push the pattern to `const sufixSpecs = ['.spec', '.test', '_spec', '_test']`.
The problem is if your code is in another path: the extension today is able to looking just for the `_spec.ext` pattern in another path. The `sufixSpecs` should be able to working in a different path too.

The original code is very ugly and it has a lot of bad smells, I have to create tests #1 and refactor #2 it.

**Comment by Nautigsam** [comment]
> the extension must be able to open any spec file

Do you mean in the same workspace ? Because it seems like a bad practice to have more than one naming convention in the same project. Though if it is a requirement I guess I can add it.

**Comment by lourenci** [comment]
> Do you mean in the same workspace ? Because it seems like a bad practice to have more than one naming convention in the same project. Though if it is a requirement I guess I can add it.

I've worked in projects with a specific pattern for backend and another one for front-end. I started this extension with it in my mind. I very appreciate your contribution.

**Comment by Nautigsam** [comment]
I added a way to specify multiple patterns. I hope it meets your expectations.

**Comment by lourenci** [comment]
What if we looking for a pre-defined list of default patterns plus an user pre-defined list of patterns? I really enjoy the idea of the user simply download the extension and it just works without any configuration. What do you think about it?

**Comment by Nautigsam** [comment]
I agree, I added the patterns that you defined in your code. I also updated the README file.

**Comment by lourenci** [comment]
I can't switch to the right spec file when there is another spec file with the same name.

An example of this is when I have `index.js` files, very common in front-end development. I could have a structure like that:

* path1
  * index.js
  * index.spec.js
* path2
  * index.js
  * index.spec.js

When I am in `path1/index.js` file, the switch have to be to `path1/index.spec.js`. It is not happening.

I could have a more complex structure like that:
* app
  * path1
    * index.js
  * path2
    * index.js
* spec
  * path1
    * index.spec.js
  * path2
    * index.spec.js

**Comment by Nautigsam** [comment]
I see, we should search for multiple spec files and then cleverly choose the right one. I'll think about that.

**Comment by Nautigsam** [comment]
I chose to compare paths using string similarity measure. I don't guarantee it will work in every file hierarchy but it works in the ones you presented.

**Comment by lourenci** [comment]
@Nautigsam, thanks, but I can't break what is working for the people now. What I can do for you is put your pattern in that array of patterns.

Or, you can change your pull request to not break what is working now.

**Comment by Nautigsam** [comment]
@lourenci Thanks for your feedback and your advices, but in the end I think that would be better I create my own extension. We clearly don't have the same needs. Sorry for the time it took.

**Pull request closed without merging**
